---

- name: ACI CNI | Set cni directory permissions
  file:
    path: /opt/cni/bin
    state: directory
    owner: kube
    recurse: true
    mode: 0755

- name: ACI CNI | Copy cni plugins
  unarchive:
    src: "{{ local_release_dir }}/cni-plugins-{{ image_arch }}-{{ cni_version }}.tgz"
    dest: "/opt/cni/bin"
    mode: 0755
    remote_src: yes

- name: Reload Kubelet to switch to CNI
  service:
    name: kubelet
    state: restarted

# Get interface ID by IP address
- set_fact:
    target_interface: "{{ item }}"
  when: >
    (hostvars[inventory_hostname]['ansible_%s' % item]|default({}))
    .get('ipv4', {}).get('address') == hostvars[inventory_hostname].ip
  with_items:
    - "{{ ansible_interfaces }}"

- name: Config DHCP for ACI CNI
  template: src=dhclient.conf.j2 dest="/etc/dhcp/dhclient.conf"
        
